[project]
name = "doc-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.86.0",
    "dotenv>=0.9.9",
    "exa-py>=2.10.2",
    "json-repair>=0.58.7",
    "langfuse>=2.0.0,<3.0.0",
    "openai>=2.30.0",
    "python-docx>=1.2.0",
    "pyyaml>=6.0.3",
    "streamlit>=1.55.0",
    "watchdog>=6.0.0",
]
